# Of the Nouns [اسْما]{.ar}

## Of Genders [جِنْس]{.ar}

55\. The reader will soon perceive with pleasure a great resemblance 
between the Persian and English languages, in the facility and simplicity 
of their form and construction ; both have no difference of termination 
to mark the gender, either in substantives or adjectives : all inanimate 
things are neuter ; and, animals of different sexes, either have different 
names, as [پِسر]{.ar} [pisar]{.trn}, a son , a boy ; [کنِیز]{.ar} [kanIz]{.trn}, a girl ; [اسْپ]{.ar} [asp]{.trn}, a horse ; 
[مادِیاں]{.ar} [madiyaN]{.trn}, a mare ; or are distinguished by the words [نر]{.ar} [nar]{.trn}, male, 
and [ماده]{.ar} [mAdah]{.trn} female; as [شیرِ نر]{.ar} [$Er-e nar]{.trn}, a lion ; [شیرِ ماده]{.ar} [$Er-e mAdah]{.trn},
a lioness ; these particles, however, are usually applied to irrational beings. 

56\. Arabic words indeed are often made feminine by receiving a 
silent ([خفی]{.ar} Art. 29) final [ه]{.ar}, as [معْشُوق]{.ar} [ma!$Uq]{.trn}, a friend; amicus, 
[معْشُوقه]{.ar} [ma!$Uqah]{.trn} , a mistress ; amica, as in this verse : 

[گُل در بر وَ مَےْ بر کفُّ و معْشُوقه بکامسْت]{.ar}

The rose in my bosom, the wine on my palm, and the beloved is to my 
desire. 

57\. But, if such noun do not signify a rational being, they consider it 
as neuter, and change the final [ة]{.ar} into [ت]{.ar}, and drop the ([◌ٌ]{.ar}) [tanwIn]{.trn2}, as 
[نِعْمةٌ]{.ar} [ni!matun]{.trn}, a benefit, [نِعْمت]{.ar}: and, indeed, nouns ending in [ت]{.ar}, are, 
for the most part, borrowed from the Arabs. 


