#!/bin/sh
Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook', clean = FALSE)"
cp -R fonts _book/
#Rscript -e "bookdown::render_book('index.Rmd','bookdown::epub_book')"
#Rscript -e "bookdown::render_book('index.Rmd','pdf_document')"
Rscript -e "bookdown::render_book('index.Rmd','bookdown::pdf_book')"

